### ISSUE TITLE
Vieille session

### ISSUE THREAD

**Issue by tleb** [Projet-Herve/HerveSys#2]
Si il y a une vieille session qui traine mais que l'utilisateur n'est pas dans la liste des utilisateurs connus, on a une joli erreur : 

```
# Reste de la traceback...
File "/home/tleb/sd/Prog/python/HerveSys/templates/default/design.html", line 29, in top-level template code
    <a>{{session["utilisateur"]}}</a> {% for i in myapp.users[session["utilisateur"]]["menu"] %}
  File "/home/tleb/.local/share/virtualenvs/herve/lib/python3.5/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'tleb'
```

**Comment by JulesMichael** [comment]
Humm j'ai jamais eu ce problème. Y a t-il un moyen de le recréer ou de le simuler ?

**Comment by tleb** [comment]
Comment je suis tombé dessus :

1. Installer le projet avec virtualenv
2. `python __main__.py run`
3. Créer un compte
4. Arrêter le serveur web
6. Installer une seconde version du projet et le lancer (pour reset le stockage)

**Comment by JulesMichael** [comment]
Je voie, donc l'utilisateur n'était plus reconnu. Merci, je vais ajouter une petite sécurité.

**Comment by tleb** [comment]
Oui, il s'agit d'un tout petit test à faire, vérifier que la valeur en session est un utilisateur valide.
